# Generated by Django 3.1.2 on 2020-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='written_date',
            field=models.DateTimeField(db_column='written_date', null=True),
        ),
    ]
