# Generated by Django 3.1.2 on 2020-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0002_qna_written_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_user',
            name='password',
            field=models.CharField(db_column='password', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitter_user',
            name='password',
            field=models.CharField(db_column='password', max_length=50, null=True),
        ),
    ]
