# Generated by Django 3.1.2 on 2020-11-19 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0003_auto_20201118_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='written_date',
        ),
        migrations.AddField(
            model_name='parent_user',
            name='member_id',
            field=models.CharField(db_column='member_id', default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='qna',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='written_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter_user',
            name='member_id',
            field=models.CharField(db_column='member_id', default='0', max_length=20),
        ),
    ]
