# Generated by Django 3.1.2 on 2020-11-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0004_auto_20201119_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_user',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='sitter_user',
            name='member_id',
        ),
        migrations.AlterField(
            model_name='message_hitory',
            name='other_owner_id',
            field=models.CharField(db_column='other_owner_id', max_length=20),
        ),
        migrations.AlterField(
            model_name='message_hitory',
            name='owner_id',
            field=models.CharField(db_column='owner_id', max_length=20),
        ),
        migrations.AlterModelTable(
            name='work_condition',
            table='work_condition',
        ),
    ]
