# Generated by Django 3.1.2 on 2020-11-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0005_auto_20201122_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.CharField(db_column='receiver_id', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(db_column='sender_id', max_length=20),
        ),
    ]
