# Generated by Django 3.1.2 on 2020-11-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0007_auto_20201123_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_post',
            name='writer_name',
            field=models.CharField(db_column='writer_name', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitter_post',
            name='writer_name',
            field=models.CharField(db_column='writer_name', max_length=80, null=True),
        ),
    ]
