# Generated by Django 3.1.2 on 2020-11-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0008_auto_20201123_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_hitory',
            name='sent_date',
            field=models.DateTimeField(db_column='sent_date', null=True),
        ),
    ]
