# Generated by Django 3.1.2 on 2020-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0009_message_hitory_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, db_column='sent_date'),
        ),
    ]
