# Generated by Django 3.1.2 on 2020-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0010_auto_20201124_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True, db_column='sent_date')),
                ('message_status', models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], db_column='message_status', default='U', max_length=1)),
                ('owner_id', models.CharField(db_column='owner_id', max_length=20)),
                ('other_owner_id', models.CharField(db_column='other_owner_id', max_length=20)),
            ],
            options={
                'db_table': 'message_hitory',
                'unique_together': {('owner_id', 'other_owner_id')},
            },
        ),
        migrations.DeleteModel(
            name='Message_Hitory',
        ),
    ]
