# Generated by Django 3.1.2 on 2020-11-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0011_auto_20201124_1750'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message_history',
            table='Message_History',
        ),
    ]
