# Generated by Django 3.1.2 on 2020-11-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0012_auto_20201124_1806'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message_history',
            table='message_history',
        ),
    ]
