# Generated by Django 3.1.2 on 2020-11-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0013_auto_20201124_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_post',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ihelprapp.application'),
        ),
    ]
