# Generated by Django 3.1.2 on 2020-11-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0014_auto_20201125_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_user_id',
            field=models.CharField(db_column='reviewed_user_id', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_id',
            field=models.CharField(db_column='reviewer_id', max_length=20),
        ),
    ]
