# Generated by Django 3.1.2 on 2020-11-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0015_auto_20201126_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(db_column='post_id')),
                ('post_owner_id', models.IntegerField(db_column='post_owner_id')),
                ('application_id', models.IntegerField(db_column='application_id')),
                ('applicant_id', models.IntegerField(db_column='applicant_id')),
            ],
            options={
                'db_table': 'Application_Manager',
                'unique_together': {('post_id', 'application_id')},
            },
        ),
        migrations.CreateModel(
            name='User_Application_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ihelprapp.application')),
            ],
            options={
                'db_table': 'User_Application_Manager',
            },
        ),
        migrations.RemoveField(
            model_name='parent_post',
            name='applicant_list',
        ),
        migrations.RemoveField(
            model_name='parent_user',
            name='post',
        ),
        migrations.RemoveField(
            model_name='sitter_user',
            name='application',
        ),
        migrations.RemoveField(
            model_name='sitter_user',
            name='post',
        ),
        migrations.DeleteModel(
            name='Applicant_List',
        ),
        migrations.AddField(
            model_name='user_application_manager',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ihelprapp.sitter_user'),
        ),
    ]
