# Generated by Django 3.1.2 on 2020-11-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0016_auto_20201129_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_application_manager',
            old_name='user_id',
            new_name='user',
        ),
    ]
