# Generated by Django 3.1.2 on 2020-11-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0018_auto_20201130_1430'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application_manager',
            table='application_manager',
        ),
        migrations.AlterModelTable(
            name='user_application_manager',
            table='user_application_manager',
        ),
    ]
