# Generated by Django 3.1.2 on 2020-11-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0019_auto_20201130_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_manager',
            name='date',
        ),
    ]
