# Generated by Django 3.1.2 on 2020-12-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0021_application_manager_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user_id',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ihelprapp.sitter_user'),
        ),
        migrations.AlterField(
            model_name='application',
            name='attached_file',
            field=models.FileField(upload_to='media/uploads/'),
        ),
        migrations.AlterUniqueTogether(
            name='application_manager',
            unique_together={('post', 'applicant_id')},
        ),
        migrations.DeleteModel(
            name='User_Application_Manager',
        ),
    ]
