# Generated by Django 3.1.2 on 2020-12-02 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ihelprapp', '0024_auto_20201202_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attached_file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
